#!/bin/bash

NAME="main"
DEST="/pdfs/segundo/resum_programacio_no_lineal.pdf"
MSG="PDF resum programacio no lineal actualitzat :blush: :smirk:"

source ../upload_file.sh

upload "$NAME" "$DEST" "$MSG"
